#!/usr/bin/env python3
import readline

def main():
    try:
        print(f"\nTotal prime numbers between {(s := int(input('Where do you want to start?: ')))} and {(n := int(input('Where do you want to stop?: ')))} is: {sum((print(i, end=' ') or 1) for i in range(s, n + 1) if i > 1 and all(i % y for y in range(2, int(__import__('math').sqrt(i)) + 1)))}")
    except KeyboardInterrupt:
        print("\n\nGoodbye!")

if __name__ == "__main__":
    main()
